### ISSUE TITLE
Bug: k8s部署的情况下，无法解析url后缀

### ISSUE THREAD

**Issue by yisany** [chat2db/Chat2DB#1124]
### Chat2DB Version

3.1.19

### Describe the bug

我在k8s集群中部署chat2db，镜像版本：`chat2db/chat2db:3.1.19`

使用了Ingress来提供访问，理想的url为：

> http://myhost.com/ide-db

Ingress具体配置如下：

``` yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat2db
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300s"
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: chat2db
                port:
                  number: 10824
            path: /ide-db(/|$)(.*)
            pathType: ImplementationSpecific
```

但我这样配置之后，访问之后发现不行，所有的api请求会无视我配置的第一层路径。

``` bash
# 理想的请求路径
http://myhost.com/ide-db/login?callback=/
# 实际的请求路径
http://myhost.com/login?callback=/
```

目前没有条件提供二级域名，只能使用url后缀的方式，希望可以支持该功能。
